# https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simpleoperators.szikes.io
spec:
  group: szikes.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                image:
                  description: 'Specify the image with optionally tag.'
                  type: string
                replicas:
                  description: 'Specify the number of replicas. Maximum: 10 Default: 1'
                  type: integer
                  minimum: 1
                  maximum: 10
                  default: 1
              required:
                - host
                - image
            status: # TODO: how to read? only via API?
              type: object
              properties:
                availableReplicas:
                  type: integer
  scope: Namespaced
  names:
    plural: simpleoperators
    singular: simpleoperator
    kind: SimpleOperator
    shortNames:
    - so
