---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators/finalizers
  verbs:
  - update
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators/status
  verbs:
  - get
  - patch
  - update
