# permissions for end users to edit simpleoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: simpleoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: simple-kubernetes-operator
    app.kubernetes.io/part-of: simple-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: simpleoperator-editor-role
rules:
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators/status
  verbs:
  - get
