# permissions for end users to edit simpleoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: temp
    app.kubernetes.io/managed-by: kustomize
  name: simpleoperator-editor-role
rules:
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simpleoperator.szikes.io
  resources:
  - simpleoperators/status
  verbs:
  - get
