apiVersion: simpleoperator.szikes.io/v1alpha1
kind: SimpleOperator
metadata:
  labels:
    app.kubernetes.io/name: simpleoperator
    app.kubernetes.io/instance: simpleoperator-sample
    app.kubernetes.io/part-of: simple-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: simple-kubernetes-operator
  name: simpleoperator-sample
spec:
  # TODO(user): Add fields here
  host: szikes.127.0.0.1.nip.io
  image: nginx:latest
  #replicas: 5
